name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #检出最新代码
      - name: Install Dependencies
        run: npm install # 安装依赖
      - name: Build
        run: npm run build # 执行构建
      - name: Create or update Build Branch
        run: |
          git checkout -B build origin/build
          git add .
          git commit -m "Add build artifacts"
          git push -f origin build
